<html>
<head>
  <meta name="generator" charset="gb2312" content= "HTML Tidy for Windows (vers 14 February 2006), see www.w3.org">
  <title>洗手间位置占用监控系统</title>
</head>

<body bgColor=#ffffff leftMargin=0 topMargin=10 marginwidth="0" marginheight="0">
<div align=center style="width: 800; height: 800">
<table style="border: 1px solid #000080" height=800 cellSpacing=0 cellPadding=0 width=800>
 <tbody>
 <tr bgColor=#EEEEEE>
  <td style="border-bottom: 1px solid #000080" vAlign=center noWrap height=70 margin=50 width=600>
   <h1 align="center"><font face="song" color="#006699">洗手间位置占用监控系统</font></h1>
  </td>
  <td style="border-bottom: 1px solid #000080" vAlign=center noWrap height=73 width=230>
   <a href="http://www.keil.com"><img border="0" src="keil.gif" align="left" width="151" height=47></a>
  </td>
  <td style="border-bottom: 1px solid #000080" align=center vAlign=center noWrap width=70> 
   <a href="index.htm"><img border=0 src="home.png" width=31 height=29></a>
  </td>
 </tr>
 <tr>
  <td colSpan=5 height=380 width=815 vAlign=top background="llblue.jpg" style="background-repeat: repeat-y;">
   <div align=center>
    <center><font face="song">
     <table width="90%" border=0 align=center>
      <tbody><tr>
       <td width="95%">
